export const country = [
  {
    label: "Afghanistan",
    name: "afghanistan",
    value: "AFG",
    korNm: "아프가니스탄",
    status: true,
  },
  {
    label: "Albania",
    name: "albania",
    value: "ALB",
    korNm: "알바니아",
    status: true,
  },
  {
    label: "Algeria",
    name: "algeria",
    value: "DZA",
    korNm: "알제리",
    status: true,
  },
  {
    label: "Andorra",
    name: "andorra",
    value: "AND",
    korNm: "안도라",
    status: true,
  },
  {
    label: "Angola",
    name: "angola",
    value: "AGO",
    korNm: "앙골라",
    status: true,
  },
  {
    label: "Antiguaand barbuda",
    name: "antigua-and-barbuda",
    value: "ATG",
    korNm: "앤티과바부다",
    status: true,
  },
  {
    label: "Argentina",
    name: "argentina",
    value: "ARG",
    korNm: "아르헨티나",
    status: true,
  },
  {
    label: "Armenia",
    name: "armenia",
    value: "ARM",
    korNm: "아르메니아",
    status: true,
  },
  {
    label: "Aruba",
    name: "aruba",
    value: "ABW",
    korNm: "아루바",
    status: true,
  },
  {
    label: "Samoa",
    name: "samoa",
    value: "WSM",
    korNm: "미국령 사모아",
    status: true,
  },
  {
    label: "Australia",
    name: "australia",
    value: "AUS",
    korNm: "오스트레일리아",
    status: true,
  },
  {
    label: "Austria",
    name: "austria",
    value: "AUT",
    korNm: "오스트리아",
    status: true,
  },
  {
    label: "Azerbaijan",
    name: "azerbaijan",
    value: "AZE",
    korNm: "아제르바이잔",
    status: true,
  },
  {
    label: "Bahamas",
    name: "bahamas",
    value: "BHS",
    korNm: "바하마",
    status: true,
  },
  {
    label: "Bangladesh",
    name: "bangladesh",
    value: "BGD",
    korNm: "방글라데시",
    status: true,
  },
  {
    label: "Barbados",
    name: "barbados",
    value: "BRB",
    korNm: "바베이도즈",
    status: true,
  },
  {
    label: "Burundi",
    name: "burundi",
    value: "BDI",
    korNm: "부룬디",
    status: true,
  },
  {
    label: "Belgium",
    name: "belgium",
    value: "BEL",
    korNm: "벨기에",
    status: true,
  },
  {
    label: "Benin",
    name: "benin",
    value: "BEN",
    korNm: "베넹",
    status: true,
  },
  {
    label: "Bermuda",
    name: "bermuda",
    value: "BMU",
    korNm: "버뮤다",
    status: true,
  },
  {
    label: "Bhutan",
    name: "bhutan",
    value: "BTN",
    korNm: "부탄",
    status: true,
  },
  {
    label: "Bosnia and herzegovina",
    name: "bosnia-and-herzegovina",
    value: "BIH",
    korNm: "보스니아헤르체고비나",
    status: true,
  },
  {
    label: "Belize",
    name: "belize",
    value: "BLZ",
    korNm: "벨리즈",
    status: true,
  },
  {
    label: "Belarus",
    name: "belarus",
    value: "BLR",
    korNm: "벨라루스",
    status: true,
  },
  {
    label: "Bolivia",
    name: "bolivia",
    value: "BOL",
    korNm: "볼리비아",
    status: true,
  },
  {
    label: "Botswana",
    name: "botswana",
    value: "BWA",
    korNm: "보츠와나",
    status: true,
  },
  {
    label: "Brazil",
    name: "brazil",
    value: "BRA",
    korNm: "브라질",
    status: true,
  },
  {
    label: "Bahrain",
    name: "bahrain",
    value: "BHR",
    korNm: "바레인",
    status: true,
  },
  {
    label: "Brunei",
    name: "brunei",
    value: "BRN",
    korNm: "브루나이",
    status: true,
  },
  {
    label: "Bulgaria",
    name: "bulgaria",
    value: "BGR",
    korNm: "불가리아",
    status: true,
  },
  {
    label: "Burkina faso",
    name: "burkina-faso",
    value: "BFA",
    korNm: "부르키나파소",
    status: true,
  },
  {
    label: "Central african republic",
    name: "central-african-republic",
    value: "CAF",
    korNm: "중앙아프리카공화국",
    status: true,
  },
  {
    label: "Cambodia",
    name: "cambodia",
    value: "KHM",
    korNm: "캄보디아",
    status: true,
  },
  {
    label: "Canada",
    name: "canada",
    value: "CAN",
    korNm: "캐나다",
    status: true,
  },
  {
    label: "Cayman",
    name: "cayman-islands",
    value: "CYM",
    korNm: "케이먼 제도",
    status: true,
  },
  {
    label: "Republic of the congo",
    name: "republic-of-the-congo",
    value: "COG",
    korNm: "콩고",
    status: true,
  },
  {
    label: "Chad",
    name: "chad",
    value: "TCD",
    korNm: "차드",
    status: true,
  },
  {
    label: "Chile",
    name: "chile",
    value: "CHL",
    korNm: "칠레",
    status: true,
  },
  {
    label: "China",
    name: "china",
    value: "CHN",
    korNm: "중국",
    status: true,
  },
  {
    label: "Côte d’Ivoire",
    name: "coted_d_ivoire",
    value: "CIV",
    korNm: "코트디부아르",
    status: true,
  },
  {
    label: "Cameroon",
    name: "cameroon",
    value: "CMR",
    korNm: "카메룬",
    status: true,
  },
  {
    label: "Democratic republic of congo",
    name: "democratic-republic-of-congo",
    value: "COD",
    korNm: "콩고민주공화국",
    status: true,
  },
  {
    label: "Cook",
    name: "cook-islands",
    value: "COK",
    korNm: "쿡",
    status: true,
  },
  {
    label: "Colombia",
    name: "colombia",
    value: "COL",
    korNm: "콜롬비아",
    status: true,
  },
  {
    label: "Comoros",
    name: "comoros",
    value: "COM",
    korNm: "코모로",
    status: true,
  },
  {
    label: "Cape verde",
    name: "cape-verde",
    value: "CPV",
    korNm: "케이프베르데",
    status: true,
  },
  {
    label: "Costa_rica",
    name: "costa-rica",
    value: "CRI",
    korNm: "코스타리카",
    status: true,
  },
  {
    label: "Croatia",
    name: "croatia",
    value: "HRV",
    korNm: "크로아티아",
    status: true,
  },
  {
    label: "Cuba",
    name: "cuba",
    value: "CUB",
    korNm: "쿠바",
    status: true,
  },
  {
    label: "Cyprus",
    name: "cyprus",
    value: "CYP",
    korNm: "키프러스",
    status: true,
  },
  {
    label: "Czech republic",
    name: "czech-republic",
    value: "CZE",
    korNm: "체코",
    status: true,
  },
  {
    label: "Denmark",
    name: "denmark",
    value: "DNK",
    korNm: "덴마크",
    status: true,
  },
  {
    label: "Djibouti",
    name: "djibouti",
    value: "DJI",
    korNm: "지부티",
    status: true,
  },
  {
    label: "Dominica",
    name: "dominica",
    value: "DMA",
    korNm: "도미니카 연방",
    status: true,
  },
  {
    label: "Dominican republic",
    name: "dominican-republic",
    value: "DOM",
    korNm: "도미니카 공화국",
    status: true,
  },
  {
    label: "Ecuador",
    name: "ecuador",
    value: "ECU",
    korNm: "에콰도르",
    status: true,
  },
  {
    label: "Egypt",
    name: "egypt",
    value: "EGY",
    korNm: "이집트",
    status: true,
  },
  {
    label: "Eritrea",
    name: "eritrea",
    value: "ERI",
    korNm: "에리트레아",
    status: true,
  },
  {
    label: "Salvador",
    name: "salvador",
    value: "SLV",
    korNm: "엘살바도르",
    status: true,
  },
  {
    label: "Spain",
    name: "spain",
    value: "ESP",
    korNm: "스페인",
    status: true,
  },
  {
    label: "Estonia",
    name: "estonia",
    value: "EST",
    korNm: "에스토니아",
    status: true,
  },
  {
    label: "Ethiopia",
    name: "ethiopia",
    value: "ETH",
    korNm: "에티오피아",
    status: true,
  },
  {
    label: "Fiji",
    name: "fiji",
    value: "FJI",
    korNm: "피지",
    status: true,
  },
  {
    label: "Finland",
    name: "finland",
    value: "FIN",
    korNm: "핀란드",
    status: true,
  },
  {
    label: "France",
    name: "france",
    value: "FRA",
    korNm: "프랑스",
    status: true,
  },
  {
    label: "Micronesia",
    name: "micronesia",
    value: "FSM",
    korNm: "미크로네시아",
    status: true,
  },
  {
    label: "Gabon",
    name: "gabon",
    value: "GAB",
    korNm: "가봉",
    status: true,
  },
  {
    label: "Gambia",
    name: "gambia",
    value: "GMB",
    korNm: "감비아",
    status: true,
  },
  {
    label: "United_kingdom",
    name: "united-kingdom",
    value: "GBR",
    korNm: "영국",
    status: true,
  },
  {
    label: "Guinea bissau",
    name: "guinea-bissau",
    value: "GNB",
    korNm: "기니비사우",
    status: true,
  },
  {
    label: "Georgia",
    name: "georgia",
    value: "GEO",
    korNm: "그루지아",
    status: true,
  },
  {
    label: "Equatorial guinea",
    name: "equatorial-guinea",
    value: "GNQ",
    korNm: "적도 기니",
    status: true,
  },
  {
    label: "Germany",
    name: "germany",
    value: "DEU",
    korNm: "독일",
    status: true,
  },
  {
    label: "Ghana",
    name: "ghana",
    value: "GHA",
    korNm: "가나",
    status: true,
  },
  {
    label: "Greece",
    name: "greece",
    value: "GRC",
    korNm: "그리스",
    status: true,
  },
  {
    label: "Grenada",
    name: "grenada",
    value: "GRD",
    korNm: "그레나다",
    status: true,
  },
  {
    label: "Guatemala",
    name: "guatemala",
    value: "GTM",
    korNm: "과테말라",
    status: true,
  },
  {
    label: "Guinea",
    name: "guinea",
    value: "GIN",
    korNm: "기니",
    status: true,
  },
  {
    label: "Guam",
    name: "guam",
    value: "GUM",
    korNm: "괌",
    status: true,
  },
  {
    label: "Guyana",
    name: "guyana",
    value: "GUY",
    korNm: "가이아나",
    status: true,
  },
  {
    label: "Haiti",
    name: "haiti",
    value: "HTI",
    korNm: "아이티",
    status: true,
  },
  {
    label: "Hong Kong",
    name: "hong-kong",
    value: "HKG",
    korNm: "홍콩",
    status: true,
  },
  {
    label: "Honduras",
    name: "honduras",
    value: "HND",
    korNm: "온두라스",
    status: true,
  },
  {
    label: "Hungary",
    name: "hungary",
    value: "HUN",
    korNm: "헝가리",
    status: true,
  },
  {
    label: "Indonesia",
    name: "indonesia",
    value: "IDN",
    korNm: "인도네시아",
    status: true,
  },
  {
    label: "India",
    name: "india",
    value: "IND",
    korNm: "인도",
    status: true,
  },
  {
    label: "Iran",
    name: "iran",
    value: "IRN",
    korNm: "이란",
    status: false,
  },
  {
    label: "Ireland",
    name: "ireland",
    value: "IRL",
    korNm: "아일랜드",
    status: true,
  },
  {
    label: "Iraq",
    name: "iraq",
    value: "IRQ",
    korNm: "이라크",
    status: true,
  },
  {
    label: "Iceland",
    name: "iceland",
    value: "ISL",
    korNm: "아이슬란드",
    status: true,
  },
  {
    label: "Israel",
    name: "israel",
    value: "ISR",
    korNm: "이스라엘",
    status: true,
  },
  {
    label: "Italy",
    name: "italy",
    value: "ITA",
    korNm: "이탈리아",
    status: true,
  },
  {
    label: "British virgin islands",
    name: "british-virgin-islands",
    value: "VGB",
    korNm: "영국령 버진",
    status: true,
  },
  {
    label: "Jamaica",
    name: "jamaica",
    value: "JAM",
    korNm: "자메이카",
    status: true,
  },
  {
    label: "Jordan",
    name: "jordan",
    value: "JOR",
    korNm: "요르단",
    status: true,
  },
  {
    label: "Japan",
    name: "japan",
    value: "JPN",
    korNm: "일본",
    status: true,
  },
  {
    label: "Kazakhstan",
    name: "kazakhstan",
    value: "KAZ",
    korNm: "카자흐스탄",
    status: true,
  },
  {
    label: "Kenya",
    name: "kenya",
    value: "KEN",
    korNm: "케냐",
    status: true,
  },
  {
    label: "Kyrgyzstan",
    name: "kyrgyzstan",
    value: "KGZ",
    korNm: "키르기즈스탄",
    status: true,
  },
  {
    label: "South Korea",
    name: "south-korea",
    value: "KOR",
    korNm: "대한민국",
    status: true,
  },
  {
    label: "Saudi arabia",
    name: "saudi-arabia",
    value: "SAU",
    korNm: "사우디아라비아",
    status: true,
  },
  {
    label: "Kuwait",
    name: "kuwait",
    value: "KWT",
    korNm: "쿠웨이트",
    status: true,
  },
  {
    label: "Laos",
    name: "laos",
    value: "LAO",
    korNm: "라오스",
    status: true,
  },
  {
    label: "Latvia",
    name: "latvia",
    value: "LVA",
    korNm: "라트비아",
    status: true,
  },
  {
    label: "Libya",
    name: "libya",
    value: "LBY",
    korNm: "리비아",
    status: true,
  },
  {
    label: "Liberia",
    name: "liberia",
    value: "LBR",
    korNm: "라이베리아",
    status: true,
  },
  {
    label: "St. lucia",
    name: "st-lucia",
    value: "LCA",
    korNm: "세인트루시아",
    status: true,
  },
  {
    label: "Lesotho",
    name: "lesotho",
    value: "LSO",
    korNm: "레소토",
    status: true,
  },
  {
    label: "Lebanon",
    name: "lebanon",
    value: "LBN",
    korNm: "레바논",
    status: true,
  },
  {
    label: "Liechtenstein",
    name: "liechtenstein",
    value: "LIE",
    korNm: "리히텐슈타인",
    status: true,
  },
  {
    label: "Lithuania",
    name: "lithuania",
    value: "LTU",
    korNm: "리투아니아",
    status: true,
  },
  {
    label: "Luxembourg",
    name: "luxembourg",
    value: "LUX",
    korNm: "룩셈부르크",
    status: true,
  },
  {
    label: "Madagascar",
    name: "madagascar",
    value: "MDG",
    korNm: "마다가스카르",
    status: true,
  },
  {
    label: "Morocco",
    name: "morocco",
    value: "MAR",
    korNm: "모로코",
    status: true,
  },
  {
    label: "Malaysia",
    name: "malaysia",
    value: "MYS",
    korNm: "말레이시아",
    status: true,
  },
  {
    label: "Malawi",
    name: "malawi",
    value: "MWI",
    korNm: "말라위",
    status: true,
  },
  {
    label: "Moldova",
    name: "moldova",
    value: "MDA",
    korNm: "몰도바",
    status: true,
  },
  {
    label: "Maldives",
    name: "maldives",
    value: "MDV",
    korNm: "몰디브",
    status: true,
  },
  {
    label: "Mexico",
    name: "mexico",
    value: "MEX",
    korNm: "멕시코",
    status: true,
  },
  {
    label: "Mongolia",
    name: "mongolia",
    value: "MNG",
    korNm: "몽골",
    status: true,
  },
  {
    label: "Republic of macedonia",
    name: "republic-of-macedonia",
    value: "MKD",
    korNm: "마케도니아",
    status: true,
  },
  {
    label: "Mali",
    name: "mali",
    value: "MLI",
    korNm: "말리",
    status: true,
  },
  {
    label: "Malta",
    name: "malta",
    value: "MLT",
    korNm: "몰타",
    status: true,
  },
  {
    label: "Monaco",
    name: "monaco",
    value: "MCO",
    korNm: "모나코",
    status: true,
  },
  {
    label: "Mozambique",
    name: "mozambique",
    value: "MOZ",
    korNm: "모잠비크",
    status: true,
  },
  {
    label: "Mauritius",
    name: "mauritius",
    value: "MUS",
    korNm: "모리셔스",
    status: true,
  },
  {
    label: "Mauritania",
    name: "mauritania",
    value: "MRT",
    korNm: "모리타니아",
    status: true,
  },
  {
    label: "Myanmar",
    name: "myanmar",
    value: "MMR",
    korNm: "미얀마",
    status: true,
  },
  {
    label: "Namibia",
    name: "namibia",
    value: "NAM",
    korNm: "나미비아",
    status: true,
  },
  {
    label: "Nauru",
    name: "nauru",
    value: "NRU",
    korNm: "나우루",
    status: true,
  },
  {
    label: "Netherlands",
    name: "netherlands",
    value: "NLD",
    korNm: "네덜란드",
    status: true,
  },
  {
    label: "Netherlands Antilles",
    name: "netherlands-antilles",
    value: "ANT",
    korNm: "네덜란드령 안틸레스",
    status: true,
  },
  {
    label: "Nepal",
    name: "nepal",
    value: "NPL",
    korNm: "네팔",
    status: true,
  },
  {
    label: "New zealand",
    name: "new-zealand",
    value: "NZL",
    korNm: "뉴질란드",
    status: true,
  },
  {
    label: "Nicaragua",
    name: "nicaragua",
    value: "NIC",
    korNm: "니카라과",
    status: true,
  },
  {
    label: "Nigeria",
    name: "nigeria",
    value: "NGA",
    korNm: "나이지리아",
    status: true,
  },
  {
    label: "Niger",
    name: "niger",
    value: "NER",
    korNm: "니제르",
    status: true,
  },
  {
    label: "Norfolk",
    name: "norfolk",
    value: "NFK",
    korNm: "노퍽",
    status: true,
  },
  {
    label: "Norway",
    name: "norway",
    value: "NOR",
    korNm: "노르웨이",
    status: true,
  },
  {
    label: "Oman",
    name: "oman",
    value: "OMN",
    korNm: "오만",
    status: true,
  },
  {
    label: "Pakistan",
    name: "pakistan",
    value: "PAK",
    korNm: "파키스탄",
    status: true,
  },
  {
    label: "Panama",
    name: "panama",
    value: "PAN",
    korNm: "파나마",
    status: true,
  },
  {
    label: "Paraguay",
    name: "paraguay",
    value: "PRY",
    korNm: "파라과이",
    status: true,
  },
  {
    label: "Peru",
    name: "peru",
    value: "PER",
    korNm: "페루",
    status: true,
  },
  {
    label: "Philippines",
    name: "philippines",
    value: "PHL",
    korNm: "필리핀",
    status: true,
  },
  {
    label: "Palestine",
    name: "palestine",
    value: "PSE",
    korNm: "팔레스타인",
    status: true,
  },
  {
    label: "Palau",
    name: "palau",
    value: "PLW",
    korNm: "팔라우",
    status: true,
  },
  {
    label: "papua new guinea",
    name: "papua-new-guinea",
    value: "PNG",
    korNm: "파푸아뉴기니",
    status: true,
  },
  {
    label: "Republic of poland",
    name: "republic-of-poland",
    value: "POL",
    korNm: "폴란드",
    status: true,
  },
  {
    label: "Portugal",
    name: "portugal",
    value: "PRT",
    korNm: "포르투갈",
    status: true,
  },
  {
    label: "North Korea",
    name: "north-korea",
    value: "PRK",
    korNm: "북한",
    status: false,
  },
  {
    label: "Puerto Rico",
    name: "puerto-rico",
    value: "PRI",
    korNm: "푸에르토리코",
    status: true,
  },
  {
    label: "Qatar",
    name: "qatar",
    value: "QAT",
    korNm: "카타르",
    status: true,
  },
  {
    label: "Romania",
    name: "romania",
    value: "ROU",
    korNm: "루마니아",
    status: true,
  },
  {
    label: "South africa",
    name: "south-africa",
    value: "ZAF",
    korNm: "남아프리카공화국",
    status: true,
  },
  {
    label: "Russia",
    name: "russia",
    value: "RUS",
    korNm: "러시아",
    status: true,
  },
  {
    label: "Rwanda",
    name: "rwanda",
    value: "RWA",
    korNm: "르완다",
    status: true,
  },
  {
    label: "Serbia",
    name: "serbia",
    value: "SRB",
    korNm: "세르비아",
    status: true,
  },
  {
    label: "Senegal",
    name: "senegal",
    value: "SEN",
    korNm: "세네갈",
    status: true,
  },
  {
    label: "Seychelles",
    name: "seychelles",
    value: "SYC",
    korNm: "세이셸",
    status: true,
  },
  {
    label: "Singapore",
    name: "singapore",
    value: "SGP",
    korNm: "싱가포르",
    status: true,
  },
  {
    label: "Saint kitts and nevis",
    name: "saint-kitts-and-nevis",
    value: "KNA",
    korNm: "세인트 키츠 앤 네비스",
    status: true,
  },
  {
    label: "Sierra leone",
    name: "sierra-leone",
    value: "SLE",
    korNm: "시에라리온",
    status: true,
  },
  {
    label: "Slovenia",
    name: "slovenia",
    value: "SVN",
    korNm: "슬로베니아",
    status: true,
  },
  {
    label: "San Marino",
    name: "san-marino",
    value: "SMR",
    korNm: "산마리노",
    status: true,
  },
  {
    label: "Solomon islands",
    name: "solomon-islands",
    value: "SLB",
    korNm: "솔로몬",
    status: true,
  },
  {
    label: "Somalia",
    name: "somalia",
    value: "SOM",
    korNm: "소말리아",
    status: true,
  },
  {
    label: "Sri lanka",
    name: "sri-lanka",
    value: "LKA",
    korNm: "스리랑카",
    status: true,
  },
  {
    label: "Sao Tome And Principe",
    name: "sao-tome-and-principe",
    value: "STP",
    korNm: "상투메 프린시페",
    status: true,
  },
  {
    label: "Sudan",
    name: "sudan",
    value: "SDN",
    korNm: "수단",
    status: true,
  },
  {
    label: "Switzerland",
    name: "switzerland",
    value: "CHE",
    korNm: "스위스",
    status: true,
  },
  {
    label: "Surinam",
    name: "suriname",
    value: "SUR",
    korNm: "수리남",
    status: true,
  },
  {
    label: "Slovakia",
    name: "slovakia",
    value: "SVK",
    korNm: "슬로바키아",
    status: true,
  },
  {
    label: "Sweden",
    name: "sweden",
    value: "SWE",
    korNm: "스웨덴",
    status: true,
  },
  {
    label: "Swaziland",
    name: "swaziland",
    value: "SWZ",
    korNm: "스와질랜드",
    status: true,
  },
  {
    label: "Syria",
    name: "syria",
    value: "SYR",
    korNm: "시리아",
    status: true,
  },
  {
    label: "Tanzania",
    name: "tanzania",
    value: "TZA",
    korNm: "탄자니아",
    status: true,
  },
  {
    label: "Tonga",
    name: "tonga",
    value: "TON",
    korNm: "통가",
    status: true,
  },
  {
    label: "Thailand",
    name: "thailand",
    value: "THA",
    korNm: "타이",
    status: true,
  },
  {
    label: "Tajikistan",
    name: "tadzhikistan",
    value: "TJK",
    korNm: "타지키스탄",
    status: true,
  },
  {
    label: "Turkmenistan",
    name: "turkmenistan",
    value: "TKM",
    korNm: "투르크메니스탄",
    status: true,
  },
  {
    label: "Togo",
    name: "togo",
    value: "TGO",
    korNm: "토고",
    status: true,
  },
  {
    label: "Taiwan",
    name: "taiwan",
    value: "TWN",
    korNm: "대만",
    status: true,
  },
  {
    label: "Trinidad And Tobago",
    name: "trinidad-and-tobago",
    value: "TTO",
    korNm: "트리니다드 토바고",
    status: true,
  },
  {
    label: "Tunisia",
    name: "tunisia",
    value: "TUN",
    korNm: "튀니지",
    status: true,
  },
  {
    label: "Turkey",
    name: "turkey",
    value: "TUR",
    korNm: "터키",
    status: true,
  },
  {
    label: "United arab emirates",
    name: "united-arab-emirates",
    value: "ARE",
    korNm: "아랍 에미레이트",
    status: true,
  },
  {
    label: "Uganda",
    name: "uganda",
    value: "UGA",
    korNm: "우간다",
    status: true,
  },
  {
    label: "Ukraine",
    name: "ukraine",
    value: "UKR",
    korNm: "우크라이나",
    status: true,
  },
  {
    label: "Uruguay",
    name: "uruguay",
    value: "URY",
    korNm: "우루과이",
    status: true,
  },
  {
    label: "United states",
    name: "united-states",
    value: "USA",
    korNm: "미국",
    status: true,
  },
  {
    label: "United States Virgin Islands",
    name: "united-states-virgin-islands",
    value: "VIR",
    korNm: "미국령 버진",
    status: true,
  },
  {
    label: "Uzbekistan",
    name: "uzbekistn",
    value: "UZB",
    korNm: "우즈베키스탄",
    status: true,
  },
  {
    label: "Vanuatu",
    name: "vanuatu",
    value: "VUT",
    korNm: "바누아투",
    status: true,
  },
  {
    label: "Venezuela",
    name: "venezuela",
    value: "VEN",
    korNm: "베네수엘라",
    status: true,
  },
  {
    label: "Vietnam",
    name: "vietnam",
    value: "VNM",
    korNm: "베트남",
    status: true,
  },
  {
    label: "St. Vincent And the Grenadines",
    name: "st-vincent-and-the-grenadines",
    value: "VCT",
    korNm: "세인트 빈센트 그레나딘",
    status: true,
  },
  {
    label: "Yemen",
    name: "yemen",
    value: "YEM",
    korNm: "예멘",
    status: true,
  },
  {
    label: "Yugoslavia",
    name: "yugoslavia",
    value: "YUG",
    korNm: "유고슬라비아",
    status: true,
  },
  {
    label: "Zambia",
    name: "zambia",
    value: "ZMB",
    korNm: "잠비아",
    status: true,
  },
  {
    label: "Zimbabwe",
    name: "zimbabwe",
    value: "ZWE",
    korNm: "짐바브웨",
    status: true,
  },
];

export default country;
